manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.0.0
      import:
        name-allowlist:
          - cmsis          # ARM Cortex core headers
          - hal_stm32      # ST hardware abstraction (STM32F407 drivers/pinctrl/clock)
          - picolibc       # Small C library
          - segger         # SEGGER RTT debug print over ST-LINK

  self:
    path: .
